---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: httpd-d
  labels: 
    type: webserver
    author: raju
spec: 
  replicas: 3
  selector: 
    matchLabels:
      type: webserver
  template:
    metadata:
      name: httpd-pod
      labels:
        type: webserver
    spec: 
      containers: 
        - name: httpd-pod
          image: httpd
...
