---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-deployment
  labels: 
    type: voting-app
    author: raju
spec:
  replicas: 2
  selector: 
    matchLabels:  
      type: voting-app
  template:
    metadata:
      name: voting-app-pod
      labels:
        type: voting-app
    spec:
      containers:
        - name: voting-app-pod
          image: dockersamples/examplevotingapp_vote
...
